server:
  port: 15000
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: wemirr-platform-gateway
  config:
    import:
      - optional:nacos:${spring.application.name}.properties
      - optional:nacos:redis.properties
      - optional:nacos:cloud-default.yaml
      - optional:classpath:gateway-swagger.yaml
      - optional:classpath:gateway-route.yaml
  cloud:
    nacos:
      server-addr: ${NACOS_HOST:nacos}:${NACOS_PORT:8848}
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
        namespace: v4-dev
      config:
        server-addr: ${spring.cloud.nacos.server-addr}
        namespace: v4-dev
  # Redis 配置 (默认使用环境变量)
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
