knife4j:
  gateway:
    enabled: true
    strategy: manual
    routes:
      - name: IAM Server
        url: /iam/v3/api-docs?group=default
        context-path: /iam
        service-name: wemirr-platform-iam
        order: 2
      - name: Dev Suite
        url: /suite/v3/api-docs?group=default
        context-path: /suite
        service-name: wemirr-platform-suite
        order: 3
      - name: Wms 存储管理
        url: /wms/v3/api-docs?group=default
        context-path: /wms
        service-name: wemirr-platform-wms
        order: 3
      - name: Tms 运输管理
        url: /tms/v3/api-docs?group=default
        context-path: /tms
        service-name: wemirr-platform-tms
        order: 4
      - name: BPM 审批中心
        url: /tms/v3/api-docs?group=default
        context-path: /tms
        service-name: wemirr-platform-tms
        order: 4